services:
  postgres:
    image: postgres
    container_name: inventory_springboot_postgres
    restart: always
    environment:
      # Nombre de la db
      - POSTGRES_DB=${DB_NAME}
      # Si se tiene un usuario diferente de postgres
      #- POSTGRES_USER=mi_usuario
      - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"